### ISSUE TITLE
virtualenv 20.x

### ISSUE THREAD

**Issue by asottile** [conda-forge/virtualenv-feedstock#32]
the [pre-commit](https://github.com/conda-forge/pre-commit-feedstock) feedstock is currently broken due to missing virtualenv 20.x

are there plans to update this? virtualenv 20 has been out for several months now

CC
    @kalefranz
    @mingwandroid

**Comment by nicoddemus** [comment]
https://github.com/conda-forge/staged-recipes/pull/11629

**Comment by nicoddemus** [comment]
Running into this issue while building though: https://github.com/pypa/virtualenv/issues/1829

**Comment by nicoddemus** [comment]
cc @xmnlab

**Comment by nicoddemus** [comment]
I have a working recipe locally, but waiting on https://github.com/conda-forge/staged-recipes/pull/11629 otherwise the build will fail anyway.

**Comment by nicoddemus** [comment]
PR is up: https://github.com/conda-forge/virtualenv-feedstock/pull/33
